baseURL = "https://blog.yelinaung.com/"
languageCode = "en-us"
title = "Random stuff"
theme = "hugo-ink"
pygmentsCodeFences = true
pygmentsStyle = "xcode"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[params]
subtitle = "My random notes"
featherIconsCDN = true
mode = "auto" # "dark" or "auto"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/yelinaung"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
tag = "tags"
