baseURL = "https://blog.yelinaung.com/"
languageCode = "en-us"
title = "Ye Lin's Random stuff"
theme = "hugo-ink"
pygmentsCodeFences = true
pygmentsStyle = "solarized-light"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate = 5
enableRobotsTXT = true

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[params]
subtitle = "My random notes"
featherIconsCDN = true
mode = "auto" # "dark" or "auto"
description = "A place where I write down stuff - what I've learned recently, my learning progress, interesting topics, books, wins/losses"
author = "Ye Lin Aung"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/yelinaung"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
tag = "tags"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5
